### ISSUE TITLE
First connection use "every" instead of "cnx_timeout"

### ISSUE THREAD

**Issue by celogeek** [shogo82148/Redis-Fast#36]
Hi,

The first connection use "every" params. By default it is set to "0.1ms" which make almost impossible to connect on a remote (though vpn) connection.
Even if the "cnx_timeout" is not set (mean no limit), it use the "every" params to try to reach the server.

I think the order should be :

first connection : cnx_timeout (if one set, or unlimit)

in case of disconnection with auto reconnect feature :
  try to connect using the cnx_timeout
  if fail, wait "every"
  retry until we reach the "reconnect"

What do you think ?

**Comment by shogo82148** [comment]
i think that, too.
it's old implementation when `cnx_timeout` has not been supported.
merged https://github.com/shogo82148/Redis-Fast/pull/37

**Comment by celogeek** [comment]
thanks
