### ISSUE TITLE
Will not reconnect to redis service over a unix socket when the redis service is restarted

### ISSUE THREAD

**Issue by rouzier** [shogo82148/Redis-Fast#41]
While doing a blpop if the redis service is restarted the Redis::Fast client will not reconnect.
However it will work if the client is killed from the redis-server.

Start your redis service listening to a unix socket

```
 redis-server --unixsocket /tmp/redis.sock
```

Run this in a separate session

```
my $redis = Redis::Fast->new(sock => '/tmp/redis.sock', reconnect => 60);

while(1) {
    my ($results) = $redis->blpop('bob',1);
    print $results // "undef","\n";
}

```

Killing the client is fine

```
redis-cli -s /tmp/redis.sock client list
redis-cli -s /tmp/redis.sock client kill /tmp/redis.sock:0
redis-cli -s /tmp/redis.sock client list
```

Restart the service the run the client list command

```
redis-cli -s /tmp/redis.sock client list
```

You will see that the client is not reconnecting or even throwing an error.
This does not happen when using tcp sockets.

**Comment by shogo82148** [comment]
I tried to reproduce this problem but reconnection works well.
Could you tell me about your environment( the version of os, perl, Redis::Fast, Redis, etc)?

**Comment by rouzier** [comment]
Thanks for the reply.
perl v5.10.1
Redis::Fast 0.16
redis-server 3.0.5
OS Centos 6
Let me know if you need anything else.

**Comment by shogo82148** [comment]
I think that it is caused by #73 .
Please try Redis::Fast v0.21.
