### ISSUE TITLE
Redis SET with EX/PX NX/XX options

### ISSUE THREAD

**Issue by 0x62ash** [shogo82148/Redis-Fast#72]
Hello,
Im get error `[set] ERR syntax error` on `$redis->set('test', 123, "EX 2");`
Does it means that Redis::Fast doesn support [SET options](https://redis.io/commands/set)?

PS.
Redis-Fast: 0.18
Redis-server: 3.0.6

**Comment by shogo82148** [comment]
No, Redis::Fast supports all SET options.
I think your code should be `$redis->set('test', 123, 'EX', 2);`.

**Comment by 0x62ash** [comment]
Stupid me...

And thank you )
