### ISSUE TITLE
Tests fail with redis-server 4.0.11

### ISSUE THREAD

**Issue by guimard** [shogo82148/Redis-Fast#80]
Hello, 
since Redis error messages have changed, t/04-pipeline.t fails. A little patch to be able to build with every redis version:
```diff
--- a/t/04-pipeline.t
+++ b/t/04-pipeline.t
@@ -36,7 +36,7 @@
 pipeline_ok 'single-command pipeline', ([set => [foo => 'bar'], 'OK'],);

 pipeline_ok 'pipeline with embedded error',
-  ([set => [clunk => 'eth'], 'OK'], [oops => [], undef, q[ERR unknown command 'OOPS']], [get => ['clunk'], 'eth'],);
+  ([set => [clunk => 'eth'], 'OK'], [get => ['clunk'], 'eth'],);

 pipeline_ok 'keys in pipelined mode',
   ([keys => ['*'], bag(qw<foo clunk>)], [keys => [], undef, q[ERR wrong number of arguments for 'keys' command]],);
```

**Comment by shogo82148** [comment]
Thank you for reporting.

It seems that https://github.com/antirez/redis/commit/9535c21515edeb71126ce02cd2e70147073996c2 breaks the test.
I'll fix it soon.

**Comment by guimard** [comment]
I tried to replace test by a regexp but without success. That's why I removed this test in Debian patch.
