### ISSUE TITLE
debug parameter on new constructor

### ISSUE THREAD

**Issue by pavelsr** [shogo82148/Redis-Fast#92]
As mentioned that [Redis::Fast compatible with Redis.pm](https://metacpan.org/pod/Redis::Fast#DESCRIPTION) it would be nice to implement `debug` parameter, similar to [Redis.pm](https://metacpan.org/pod/Redis#debug)

For some reason, it's [commented now](https://github.com/shogo82148/Redis-Fast/blob/a2d525e838163c970dcba9d545c325d2f0f5c3b6/lib/Redis/Fast.pm#L141) in source code.

**Comment by pavelsr** [comment]
Also for full compatibility with Redis.pm it would be nice to support `sentinel` and `conservative_reconnect` option. 

And it would be nice to mention that `Redis::Fast` has an additional `reconnect_on_error` param.

So full diff table between new constructor of Redis.pm and Redis::Fast now looks like

| param        				| Redis.pm      | Redis::Fast  |
| ------------------------- |:-------------:| -----:|
| sock      				| + | + |
| service      				| + | + |
| server 					| + | + |
| on_connect 				| + | + |
| password 					| + | + |
| name 						| + | + |
| reconnect 				| + | + |
| every 					| + | + |
| cnx_timeout 				| + | + |
| read_timeout 				| + | + |
| write_timeout 			| + | + |
| no_auto_connect_on_new	| + | + |
| sentinels_cnx_timeout 	| + | + |
| sentinels_write_timeout 	| + | + |
| sentinels_read_timeout 	| + | + |
| no_sentinels_list_update 	| + | + |
| sentinels 				| + | + |
| sentinel 					| + | - |
| conservative_reconnect	| + | - |
| debug      				| + | - |
| reconnect_on_error		| - | + |

**Comment by shogo82148** [comment]
`debug` option is now supported by #96 

-----

I guess that `sentinel` comes from here https://github.com/PerlRedis/perl-redis/blob/a1f9f41d83c951c469f4192de1bb8ff2f8540896/lib/Redis.pm#L52
It seems that `sentinel` is a typo of `sentinels`, because `$args{sentinel}` is only used here. it will be fixed by https://github.com/PerlRedis/perl-redis/pull/146

**Comment by shogo82148** [comment]
released v0.27
